apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nabilcsr-website-ui
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: nabilcsr
  source:
    path: website-ui
    repoURL: https://github.com/LokendraBhat/argotest.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true

#  The one CI change needed, in .gitlab-ci.yml's .gitops-deploy-templpecific step with a Helm-values edit:
# before:
#- cd "argocd-repo/$OVERLAY_PATH"                                                                                                                               
#- kustomize edit set image "$IMAGE=$IMAGE_REF"
