apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nabilcsr.fullname" . }}-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range list "/csr" "/nsse" "/ne/csr" "/ne/nsse" }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "nabilcsr.fullname" $ }}
                port: { number: {{ $.Values.service.port }} }
          {{- end }}
