apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nabilcsr.fullname" . }}-assets
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /csrassets(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "nabilcsr.fullname" . }}
                port: { number: {{ .Values.service.port }} }
