apiVersion: v1
kind: Service
metadata:
  name: {{ include "nabilcsr.fullname" . }}
spec:
  selector: {{- include "nabilcsr.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
